# 假设您已手动下载并解压主题到 themes/yinyang
# 请在手动下载完成后告诉我，我将继续配置

# Yin Yang主题配置模板
baseURL = 'https://blog.yunbiu.top/'
languageCode = 'zh-cn'
title = 'Ushaio的博客'
theme = 'yinyang'

# Yin Yang主题特定配置
[params]
  # 作者信息
  author = 'Ushaio'
  description = '一个使用Hugo和GitHub Pages构建的博客'
  
  # 社交链接
  github = 'ushaio'
  
  # 其他配置
  dateFormat = '2006-01-02'
  
[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    identifier = 'about'
    name = '关于'
    url = '/about/'
    weight = 30